Makefile
- Makefile
- initialize
- <img width="287" alt="image" src="https://user-images.githubusercontent.com/85754295/222345663-43d1b08f-c5d9-4a91-9f91-179d6298213f.png">
=> ⭐ Feature(makefile): draft makefile

include/minishell.h, include/prompt.h, main.c, prompt/prompt.c
- 누락된 항목들 등록
- promt
- <img width="616" alt="image" src="https://user-images.githubusercontent.com/85754295/222951258-7a7b2495-fb83-4a4e-8d8b-31157911b61c.png">
=> ⭐ Refact: prompt

Makefile, include/minishell.h, include/prompt.h, main.c, prompt/prompt.c, signal/signal.c
-  initialize signal c, d, \
- signal
- main
- <img width="306" alt="image" src="https://user-images.githubusercontent.com/85754295/223020705-73debdb9-f249-4c0a-a708-1074e1502141.png">
=> ⭐ New(signal): initialize signal

execute/execute.c, include/execute.h
- 단일 실행
- excute
- <img width="747" alt="image" src="https://user-images.githubusercontent.com/85754295/223015064-be85879a-0aa7-4803-8502-487ddf78ba7c.png">
=> 🐛 Bug(fork): use a fork to prevent termination

main.c
- add history
- main
https://user-images.githubusercontent.com/85754295/223022941-b7eeb74d-745c-4214-a3fd-20675bc5cc80.mov
=> ⭐ Feature(history): initialize

include/parse.h, parse/ASTtree/add_node_to_direction.c, parse/ASTtree/clear_nodes.c, parse/ASTtree/get_root_node.c, parse/ASTtree/make_ast_tree.c, parse/ASTtree/make_node.c, parse/expansion/interpret_expansion.c, parse/interpret_expansion.c, parse/is_valid_syntax.c, parse/parse.c, parse/token/add_token_to_tail.c, parse/token/create_new_token.c, parse/token/free_token_list.c, parse/token/get_last_token_in_parenthesis.c, parse/token/is_operator.c, parse/token/join_token_value.c, parse/token/set_fd_redirection_token.c, parse/token/set_normal_token.c, parse/token/set_operator_token.c, parse/token/set_quote_token.c, parse/token/set_token.c, parse/token/tokenize_line.c, test/tokenize.c
- 환경변수 치환하는 모듈 작성
- 함수 문서화
- /parse
- /include/parse.h
=> 16 feature 환경변수 치환

lib/libft.h
- `include/lib/libft.h`에 `t_list` 정의 추가
=> bug(libft): t_list 정의 추가

include/minishell.h, include/parse.h, parse/ASTtree/make_ast_tree.c, parse/ASTtree/make_node.c, parse/expansion/interpret_expansion.c, test/ast_tree.c
-  exit status 가져오는 모듈 추가
- `minishell.h`와 `parse.h` 병합
=> 20 feature exit status 가져오는 모듈 추가

Makefile, parse/token/delete_outer_quotes.c, test/ast_tree.c, test/syntax_check.c, test/tokenize.c
-  파싱부 테스트 Makefile에 추가
- (optional)
=> ✅ Test(parse): 파싱부 테스트 Makefile에 추가

parse/token/set_quote_token.c
- `make test-***` 시, 컴파일 되지 않는 오류 수정
- set_quote_token 내 `set_token()` 호출 시, 매개변수의 타입 수정
- (optional)
=> 🐛 Bug(test): make test-*** 시, 컴파일 되지 않는 오류 수정

builtin/builtin.c, builtin/ft_cd.c, builtin/ft_echo.c, builtin/ft_env.c, builtin/ft_exit.c, builtin/ft_export.c, builtin/ft_pwd.c, builtin/ft_unset.c, include/builtin.h, include/minishell.h
- add builtin feature
- dir/builtin
- (optional)
=> 47 feature builtin function draft

parse/token/set_token.c
- 리다이렉션으로 `*`가 온다면, 에러 처리
- wildcard 앞에 <, >, >>이 오면 `is_valid_redirection()`에서 `false`를 반환하게 함 
- (optional)
=> ⭐️ Feature(tokenize): wildcard 처리 시, 리다이렉션 파일로 주어질 경우에 ambiguous redirect 에러 처리

execute/execute.c, include/execute.h, include/parse.h, main.c
- excute 의사 코드 작성
- 실행부 초안 작성
- 
- (optional)
=> feat(excute): wip response parsing tree draft

builtin/builtin.c, builtin/ft_cd.c, builtin/ft_echo.c, include/builtin.h
- builtin function fix bad grammar
- 
- (optional)
=> bug(builtin): fix bad grammar

Makefile, execute/argv.c, execute/execute.c, include/error.h, include/execute.h, include/minishell.h, include/parse.h, include/utill.h, main.c, util/utils.c
- 재귀하향식 실행부 초안
- &&와 ||의 처리를 쉽게하기 위해
- 가독성 좋은 코드로 처리하기 위해
- wip
- 변경된 빌트인 함수가 필요하므로 builtin feature 먼저 머지해야 사용할 수 있음.
- 기존의 단일 명령어 실행에서 변경
- &&와 ||의 간단한 로직
- 현재 빌트인 함수만 사용가능
- (optional)
=> ⭐ Feature(execute): recursive execute draft

Makefile, builtin/builtin.c, execute/child.c, execute/execute.c, execute/path.c, execute/redirect.c, include/builtin.h, include/execute.h, include/minishell.h, include/prompt.h, include/utill.h, main.c, prompt/prompt.c, signal/signal.c, util/utils.c
- 전체적인 뼈대를 구성하였습니다.
- 이슈에 TODO list를 작성하였습니다.
-  실행 가능하게 구현
- (optional)
=> ⭐ Feature(execute): execute prototype

builtin/builtin.c, builtin/ft_unset.c, include/builtin.h
- unset 구현
- unset 시, 주어진 argv를 키로 하는 value 값을 널로 대체
- (optional)
=> ⭐️ Feature: implement builtin unset

builtin/ft_pwd.c, include/builtin.h
- `pwd` 구현
- `pwd` 구현
- (optional)
=> ⭐️ Feature: implement pwd

execute/execute.c, main.c, prompt/prompt.c, signal/signal.c
- 모든 함수에 description을 추가합니다.
- all
- (optional)
=> :shirt: chore(Description): add description

Makefile, env/cast.c, env/dict/add_to_env_dict.c, env/dict/free.c, env/initialize.c, include/env.h, include/minishell.h, main.c
- env 초기화하는 모듈 추가
- envp를 해석하여 g_var내 env_dict에 연결 리스트 형태로 저장
- (optional)
=> ⭐️ Feature: initialise env

Makefile, builtin/ft_unset.c, env/cast.c, env/dict/delete_env.c, env/dict/find_value.c, env/dict/free.c, include/env.h, include/parse.h, main.c, parse/token/expansion/interpret_expansion.c
- env를 사용하는 곳에 env dict를 사용하도록 변경
- getenv를 사용하는 곳 등에 적용
- (optional)
=> ⭐️ Feature: apply env dict to functions using env

builtin/ft_env.c, env/set_env.c, include/env.h
- env 구현
- g_var.envp를 출력
- (optional)
=> ⭐️ Feature: implement env

Makefile
- minishell 컴파일 안 됨
- makefile 업데이트
- (optional)
=> 🐛 Bug: can not compile minishell

include/parse.h, parse/ASTtree/clear_nodes.c, parse/ASTtree/make_node.c, parse/token/handle_wildcard.c
=> 🐛 Bug: sub node

builtin/ft_export.c, env/cast.c, env/set_env.c
- env를 업데이트 할 때 leaks 발생
- 유효하지 않은 형식으로 env 업데이트 가능
- env 업데이트 시, key, value free 후 새로운 env_dict 반환
- key나 value가 없다면, env 업데이트 하지 않음
- (optional)
=> 🐛 Bug: leaks env update

Makefile, builtin/ft_export.c, builtin/ft_export_util.c, include/builtin.h, include/minishell.h
- 옵션없는 export 시 export의 리스트가 나오게 변경됩니다.
- export.c
- export_util.c
- (optional)
=> ⭐ Feat(export): print export

builtin/ft_export.c
- export =가 있는 경우 조건 분기 생성
- ft_export.c
- (optional)
=> 🐛  Bug(export): add if '='
